# Generated by Django 3.2.4 on 2021-06-06 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='state_id',
            new_name='select_state',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='country_id',
            new_name='select_country',
        ),
    ]
