# Generated by Django 3.2.4 on 2021-06-07 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_auto_20210607_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='select_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stete', to='country.state'),
        ),
        migrations.AlterField(
            model_name='state',
            name='select_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Country', to='country.country'),
        ),
    ]
